import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav, Navlink } from "@/components/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background min-h-screen font-sans antialiased dark `}
      >
       {children}
      {/* <>
      <Nav>
        <Navlink href="/">Home</Navlink>
        <Navlink href="/products">Products</Navlink>
        <Navlink href="/orders">My Orders</Navlink>
      </Nav>
      <div className="container my-6">{children}</div>
    </> */}
      </body>

    </html>
  );
}  